apiVersion: apps/v1
kind: Deployment
metadata:
  name: rates-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: rates-service
  template:
    metadata:
      labels:
        app: rates-service
    spec:
      containers:
        - name: rates-service
          image: rates-service-image
          ports:
          - containerPort: 8000
          env:
            - name: WISE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: wise-credentials
                  key: token
