# -*- mode: Python -*-

# For more on Extensions, see: https://docs.tilt.dev/extensions.html
load('ext://restart_process', 'docker_build_with_restart')

gradlew = "./gradlew"
if os.name == "nt":
  gradlew = "gradlew.bat"

local_resource(
  'rates-service-compile',
  gradlew + ' bootJar && ' +
  'rm -rf build/jar-staging && ' +
  'java -Djarmode=layertools -jar build/libs/example-0.0.1-SNAPSHOT.jar extract --destination build/jar-extracted && ' +
  'rsync --delete --inplace --checksum -r build/jar-extracted/ build/jar',
  deps=['src', 'build.gradle']
)

docker_build_with_restart(
  'rates-service-image',
  './build/jar',
  entrypoint=['java', 'org.springframework.boot.loader.JarLauncher'],
  dockerfile='./Dockerfile',
  live_update=[
    sync('./build/jar/dependencies', '/app'),
    sync('./build/jar/spring-boot-loader', '/app'),
    sync('./build/jar/snapshot-dependencies', '/app'),
    sync('./build/jar/application', '/app'),
  ],
)

k8s_yaml('kubernetes.yaml')
k8s_resource('rates-service', port_forwards=8000,
             resource_deps=['rates-service-compile'])